version: "3.4"

services:
  artifactory-cpp-ce:
    container_name: artifactory-cpp-ce
    image: docker.bintray.io/jfrog/artifactory-cpp-ce:${VERSION_ARTIFACTORY_CPP_CE:-latest}
    ports:
      - "${PORT_ARTIFACTORY_CPP_CE:-8081}:8081"
      - "${PORT_ARTIFACTORY_CPP_CE_UI:-8082}:8082"
    volumes:
      - "artifactory-cpp-ce-data:/var/opt/jfrog/artifactory"
      - "./:/config/:ro"
    entrypoint: 
      sh -c "cd /var/opt/jfrog/artifactory/etc/artifactory \
      ; bash -c '[[ ! -f artifactory.config.bootstrap.xml ]] && cp /config/artifactory.config.import.xml ./' \
      ; /entrypoint-artifactory.sh" 
    networks:
      - default

volumes:
  artifactory-cpp-ce-data:
    name: "${PROJECT}_${ARTIFACTORYDATA:-artifactory-cpp-ce-data}"
    external: false
  artifactory-cpp-ce-etc:
    name: "${PROJECT}_${ARTIFACTORYDATA:-artifactory-cpp-ce-data}"
    external: false

networks:
  default:
    external:
      name: ${NETWORK:-elbb-dev}