# ===================================================
# meta infos
# ===================================================

meta:
  project: dev-environment
  include:
    - dobi.yaml
    - version.yaml
    - env/concourse/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - dev-environment-version
