# ===================================================
# meta infos
# ===================================================

meta:
  project: dev-environment
  include:
    - version.yaml
    - env/concourse/dobi.yaml
    - env/artifactory-cpp-ce/dobi.yaml
    - env/codechecker-web/dobi.yaml
