version: "3.4"

services:
  concourse-db:
    container_name: concourse-db
    image: postgres:${VERSION_POSTGRES:-latest}
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database
    volumes:
      - concourse-db-data:/database
    networks:
    - default

  concourse:
    container_name: concourse
    image: concourse/concourse:${VERSION_CONCOURSE:-latest}
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["${PORT_CONCOURSE:-8080}:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:${PORT_CONCOURSE:-8080}
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
    dns: 8.8.8.8
    networks:
      - default

  registry:
    container_name: registry
    image: registry:${VERSION_REGISTRY:-latest}
    ports: ["${PORT_REGISTRY:-5000}:5000"]
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry-data:/data
    networks:
    - default

  minio:
    container_name: minio
    image: minio/minio:${VERSION_MINIO:-latest}
    ports: ["${PORT_MINIO:-9000}:9000"]
    tty: true
    command: server /data
    environment:
      MINIO_ACCESS_KEY: localaccess
      MINIO_SECRET_KEY: localsecret
    volumes:
      - minio-data:/data
    networks:
    - default

volumes:
  concourse-db-data:
    name: "${PROJECT:-dev-env-concourse}_${CONCOURSEDBDATA:-concourse-db-data}"
    external: false

  minio-data:
    name: "${PROJECT:-dev-env-concourse}_${MINIODATA:-minio-data}"
    external: false

  registry-data:
    name: "${PROJECT:-dev-env-concourse}_${REGISTRYDATA:-registry-data}"
    external: false

networks:
  default:
    external:
      name: ${NETWORK:-elbb-dev}