version: "3.4"

services:
  concourse-db:
    image: postgres:13
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database
    volumes:
      - concourse-db-data:/database
    networks:  
    - default

  concourse:
    image: concourse/concourse:6.1.0
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
    dns: 8.8.8.8
    networks:  
      - default

  git:
    image: cirocosta/gitserver-http:latest
    ports: ["8081:80"]
    volumes:
      - ./git-repositories:/var/lib/git
    networks:  
    - default

  registry:
    image: registry:2
    ports: ["5000:5000"]
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry-data:/data    
    networks:  
    - default

  minio:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    ports: ["9000:9000"]
    tty: true
    command: server /data
    environment:
      MINIO_ACCESS_KEY: localaccess
      MINIO_SECRET_KEY: localsecret
    volumes:
      - minio-data:/data
    networks:  
    - default

volumes:
  concourse-db-data:
    name: "${PROJECT}_${CONCOURSEDBDATA}"
    external: false

  minio-data:
    name: "${PROJECT}_${MINIODATA}"
    external: false

  registry-data:
    name: "${PROJECT}_${REGISTRYDATA}"
    external: false    

networks:
  default:
